backend:
  name: github
  repo: wxidqlvk/wxidqlvk.github.io
  branch: main
  # 显式指定 GitHub 认证网关，彻底掐断它去请求 netlify
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "正文", name: "body", widget: "markdown"}
