backend:
  name: git-gateway
  repo: WXIDQLVK/wxidqlvk.github.io # 改成你的GitHub仓库地址
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "posts"
    label: "文章"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "正文", name: "body", widget: "markdown"}
